### ISSUE TITLE
Registered critical service

### ISSUE THREAD

**Issue by stevescc** [rogeralsing/Microphone#20]
Using the ConsulProvider, it is correct that a service cannot be both registered and have critical status? Because whenever the status code is critical it gets unregistered. If that is the intention I would've thought if I have a service that is responding but is critical for another reason, consul should still know about it? (I'm new to consul if this question seems obvious) Thanks

**Comment by rogeralsing** [comment]
See #31

The reaper should probably be removed from the Consul provider as it lacks knowledge on what is going on in the network.

**Comment by rogeralsing** [comment]
Reaper have been removed. critical services can still exist
