### ISSUE TITLE
Support for dotnetcore and ASP.NET 5

### ISSUE THREAD

**Issue by markrendle** [rogeralsing/Microphone#22]
Are you planning on supporting dotnetcore (and ASP.NET 5)? Seems like a logical step since you can easily run those in Docker containers, where things like Consul and etcd are most useful (especially etcd because it's baked into CoreOS).

**Comment by rogeralsing** [comment]
Absolutely, I've just not had much exposure to dotnetcore yet, so I need to read up a bit on how to package this all

**Comment by Dan-McElroy** [comment]
Hi there,

Has there been any progress on this? Not to be a pest, but I'm starting a new project and Microphone looks like it would be ideal, except that I can't use it with ASP.NET 5. Thanks!

**Comment by rogeralsing** [comment]
Ill give it a try, my understanding of .NET core is very limited so far but I guess it cant be that hard :)

**Comment by rogeralsing** [comment]
I've finally managed to get some work done on the dotnet core support, I have a dotnetcore branch now here on github.
It's not done yet but it seems mostly to be the system.configuration namespace that needs to be changed.

..to be continued

**Comment by Dan-McElroy** [comment]
Thanks for taking the time on this! Can't wait to use it.

**Comment by rogeralsing** [comment]
Asp.NET 5 support now avaiable on nuget 
https://www.nuget.org/packages/Microphone.AspNet/
