### ISSUE TITLE
Can Microphone be used with non WebAPI / Nancy windows services as well

### ISSUE THREAD

**Issue by pvandervelde** [rogeralsing/Microphone#34]
I have a set of windows services (using topshelf) that use different methods of communication than WebAPI / Nancy but I would love to use the ability to link to consul on start up. Is that possible with Microphone?

**Comment by dustinchilson** [comment]
If you implement a new [IFrameworkProvider](https://github.com/rogeralsing/Microphone/blob/dotnetcore/Microphone.Core/IFrameworkProvider.cs)
 you should be able to start up & register a service as long as you can communicate via address / port ([ServiceInformation](https://github.com/rogeralsing/Microphone/blob/dotnetcore/Microphone.Core/ServiceInformation.cs)).
