### ISSUE TITLE
Configuration to change the status check url

### ISSUE THREAD

**Issue by asrikantan80** [rogeralsing/Microphone#38]
How do i change the status check url to use my application map? Currently the health check for my application gets registered as http://172.18.16.72:5000/status. I need it configurable to be changed as http://172.18.16.72:5000/api/status. I keep seeing exceptions in consul trying to reach the former rather than latter.

2016/07/30 11:55:18 [WARN] agent: http request failed 'http://172.18.16.72:5000/status': Get http://172.18.16.72:5000/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2016/07/30 11:55:20 [WARN] agent: http request failed 'http://172.18.16.72:5000/status': Get http://172.18.16.72:5000/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by rogeralsing** [comment]
I've updated the nuget packages.
Now there is a HealthCheckPath on the Consul options.

```csharp
private static void RegisterWithConsul(Uri uri)
{
    var options = new OptionsWrapper<ConsulOptions>(new ConsulOptions
    {
        HealthCheckPath = "/api/status"
    });
    var logging = new LoggerFactory();
    var consulProvider = new ConsulProvider(logging, options);
    var serviceName = Assembly.GetEntryAssembly().GetName().Name;
    Cluster.RegisterService(uri, consulProvider, serviceName, "v1", logging.CreateLogger("Microphone.Consul"));
}
```

That would do it for you if you call Microphone manually.
