### ISSUE TITLE
'Cluster' does not contain a definition for 'Bootstrap'

### ISSUE THREAD

**Issue by MarkPieszak** [rogeralsing/Microphone#45]
```
using Microphone;
using Microphone.WebApi;
```

![image](https://cloud.githubusercontent.com/assets/2574412/20312428/77d4f96e-ab21-11e6-9e49-5c19211dd162.png)

Trying to setup Microphone etc but the only method that exists on Cluster is RegisterService. Is the documentation outdated or something? Can't get anything set up at the moment.

**Comment by rogeralsing** [comment]
The code example have been updated:
https://github.com/rogeralsing/Microphone#web-api

**Comment by MarkPieszak** [comment]
Thank you Roger! Much appreciated :+1: 
Great work by the way!
