### ISSUE TITLE
[Question]: Get Host and Port from inside Docker Container

### ISSUE THREAD

**Issue by Franklin89** [rogeralsing/Microphone#49]
I looked at the AspDotNetCoreDemo.

It uses rancher and makes it easy to retrieve the dynamic port used while spinning up the container. Is it possible to do the same with using just a normal docker host?

**Comment by rogeralsing** [comment]
The easiest way to handle this would be to just pass those as environment variables from docker into the container IMO.
And then just extract those variables via code.

**Comment by Franklin89** [comment]
I was just about to close this issue because I was just going down the wrong path anyways.

Its simple, don't need to map a port on a docker container to the host to talk to it. Any  container on the same docker network can talk to an **exposed** port on a container. And since I am writting the microservice i know what the exposed port will be.

Sorry for opening an issue for this...but sometimes writting something down helps. And btw awesome framework. :+1:
